import { Translations } from './translations.model';
export const en: Translations = {
  nav: { home: 'Home', about: 'About', services: 'Services', blog: 'Blog', contact: 'Contact', hire: 'Hire me' },
  hero: { greeting: "Hi, I'm", title: 'Sara Cardenas', subtitle: 'Full-Stack Developer building modern web apps with Java & Angular. Available for freelance & remote work.', cta_primary: 'View my work', cta_secondary: 'Contact me', available: '🟢 Available for projects' },
  about: { title: 'About', highlight: 'me', bio: "I'm a Full-Stack Developer from Colombia with hands-on experience building real products. I specialize in clean architectures using Spring Boot 3 on the backend and Angular on the frontend. I use AI as a force multiplier to deliver high-quality software faster.", stack_title: 'Tech Stack', arch_title: 'Architecture' },
  services: { title: 'What I', highlight: 'build', subtitle: 'Three ways I can help your business grow with professional software.', landing_title: 'Landing Pages', landing_desc: 'Modern, fast, SEO-optimized landing pages for businesses, professionals and entrepreneurs. Delivered in 5–10 business days.', app_title: 'Web Applications', app_desc: 'Custom web apps: admin panels, CRMs, inventory systems, booking portals and dashboards built with clean architecture.', saas_title: 'SaaS Products', saas_desc: 'Currently building AgendaFácil — a booking system for local businesses. Your idea could be next.', cta: "Let's talk" },
  blog: { title: 'Latest', highlight: 'posts', subtitle: 'Sharing what I learn about architecture, Java, Angular and building products.', read_more: 'Read more' },
  contact: { title: 'Get in', highlight: 'touch', subtitle: "Have a project in mind or want to discuss a collaboration? I'd love to hear from you.", name_label: 'Your name', email_label: 'Your email', message_label: 'Your message', send: 'Send message', success: "Message sent! I'll get back to you within 24 hours.", error: 'Something went wrong. Please email me directly at contact.astrastudio.dev@gmail.com' },
  footer: { rights: 'All rights reserved.', built_with: 'Built with Angular & ☕' },
};
