import { Translations } from './translations.model';
export const es: Translations = {
  nav: { home: 'Inicio', about: 'Sobre mí', services: 'Servicios', blog: 'Blog', contact: 'Contacto', hire: 'Contrátame' },
  hero: { greeting: 'Hola, soy', title: 'Sara Cardenas', subtitle: 'Desarrolladora Full-Stack creando aplicaciones web modernas con Java y Angular. Disponible para freelance y trabajo remoto.', cta_primary: 'Ver mi trabajo', cta_secondary: 'Contáctame', available: '🟢 Disponible para proyectos' },
  about: { title: 'Sobre', highlight: 'mí', bio: 'Soy desarrolladora Full-Stack colombiana con experiencia construyendo productos reales. Me especializo en arquitecturas limpias con Spring Boot 3 en backend y Angular en frontend. Uso IA como multiplicador para entregar software de calidad más rápido.', stack_title: 'Stack tecnológico', arch_title: 'Arquitectura' },
  services: { title: 'Qué', highlight: 'construyo', subtitle: 'Tres formas en que puedo ayudar a tu negocio a crecer con software profesional.', landing_title: 'Landing Pages', landing_desc: 'Landing pages modernas, rápidas y optimizadas para SEO para negocios, profesionales y emprendedores. Entregadas en 5–10 días hábiles.', app_title: 'Aplicaciones Web', app_desc: 'Apps web personalizadas: paneles admin, CRMs, inventarios, portales de reservas y dashboards con arquitectura limpia.', saas_title: 'Productos SaaS', saas_desc: 'Actualmente construyendo AgendaFácil — sistema de reservas para negocios locales. Tu idea podría ser la siguiente.', cta: 'Hablemos' },
  blog: { title: 'Últimos', highlight: 'posts', subtitle: 'Compartiendo lo que aprendo sobre arquitectura, Java, Angular y construcción de productos.', read_more: 'Leer más' },
  contact: { title: 'Hablemos', highlight: '', subtitle: '¿Tienes un proyecto en mente o quieres explorar una colaboración? Me encantaría escucharte.', name_label: 'Tu nombre', email_label: 'Tu correo', message_label: 'Tu mensaje', send: 'Enviar mensaje', success: '¡Mensaje enviado! Te respondo en menos de 24 horas.', error: 'Algo salió mal. Escríbeme directamente a contact.astrastudio.dev@gmail.com' },
  footer: { rights: 'Todos los derechos reservados.', built_with: 'Hecho con Angular & ☕' },
};
